// DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED FROM FILE "src/LexerParser.gold"
import gold.structures.automaton.*;
import gold.util.*;
import gold.visualization.automaton.*;
import java.lang.*;
import org.apfloat.*;
import static gold.util.GReflection.*;
@SuppressWarnings("all")
public final class LexerParser {
  static {
    gold.swing.util.GUtilities.installGoldLookAndFeel();
  }
  public static void main(String[] args) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=13;
      Object Lexer=$fix(LexerParser.createTransducer());
      $line=14;
      Object Parser2=$fix(LexerParser.createAutomaton2());
      $line=15;
      Object Parser=$fix(LexerParser.createAutomaton());
      $line=16;
      Object stdin=$fix($invokeConstructor(java.util.Scanner.class,new Object[]{$invokeField(System.class,"in",true,null)}));
      $line=17;
      System.out.println($message(new Object[]{"Desea usar el parser  que implementa directamente la gramatica (1 para SI)"}));
      $line=18;
      String mode=null;
      mode=$defaultValue(String.class);
      $line=19;
      mode=$cast(String.class,$fix(((java.util.Scanner)stdin).nextLine()));
      $line=24;
      if ($opEqualY(((java.lang.String)mode).charAt($int(0)),'1')) {
        $line=25;
        System.out.println($message(new Object[]{"usando el parser que implemeta direcatmente la gramatica"}));
        $line=26;
        GAutomataFrame.show($cast(gold.structures.automaton.IAutomaton.class,Lexer));
      }
      else {
        $line=31;
        System.out.println($message(new Object[]{"usando el parser m\u00E1s eficaz"}));
        $line=33;
        GAutomataFrame.show($cast(gold.structures.automaton.IAutomaton.class,Lexer));
      }
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,LexerParser.class,"main",$line);
    }
  }
  public static Object testParser(ITransducer M, IPushdownAutomaton P) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=46;
      java.util.Scanner sc=null;
      sc=$invokeConstructor(java.util.Scanner.class,new Object[]{$invokeField(System.class,"in",true,null)});
      $line=47;
      Object string=$fix("string");
      $line=48;
      while (true) {
        if (!($opGreatY($invokeMethod("length",string,new Object[]{}),1))) break;
        $line=49;
        System.out.println($message(new Object[]{"----------------------------"}));
        $line=50;
        System.out.println($message(new Object[]{"Digite la cadena de entrada: (para termnar la cadena vacia)"}));
        $line=51;
        string=$fix($opAdditY(((java.util.Scanner)sc).nextLine()," "));
        $line=52;
        Object result=$fix(((gold.structures.automaton.ITransducer)M).acceptsString($cast(java.lang.String.class,string)));
        $line=53;
        Object tokenStream=$fix(((gold.structures.automaton.ITransducer)M).getOutputString());
        $line=54;
        System.out.println($message(new Object[]{$opAdditY($opAdditY($opAdditY("Lexicamente, la cadena fue aceptada ",(($bool(result))?("aceptada"):("rechazada"))),". Resultado: "),tokenStream)}));
        $line=57;
        result=$fix(((gold.structures.automaton.IPushdownAutomaton)P).acceptsString($cast(java.lang.String.class,tokenStream)));
        $line=58;
        System.out.println($message(new Object[]{$opAdditY("Sintacticamente, la cadena fue ",(($bool(result))?("aceptada"):("rechazada")))}));
      }
      $line=61;
      System.out.println($message(new Object[]{"Termino la ejecucion"}));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,LexerParser.class,"testParser",$line);
    }
    return $result;
  }
  public static IPushdownAutomaton createAutomaton() {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=77;
      Object Terms=$fix(GCollections.asSet('(',')','+','*','v','n'));
      $line=78;
      Object NonTerms=$fix(GCollections.asSet('E','L'));
      $line=79;
      Object Q=$fix(GCollections.asSet("I","q","F"));
      $line=80;
      Object \u03A3=$fix(Terms);
      $line=81;
      Object \u0393=$fix($opUnionY($opUnionY(Terms,NonTerms),GCollections.asSet('$')));
      $line=82;
      Object q_0=$fix("I");
      $line=83;
      Object F=$fix(GCollections.asSet("F"));
      $line=84;
      Object M=$fix($invokeConstructor(GPushdownAutomaton.class,new Object[]{Q,\u03A3,\u0393,q_0,F}));
      $line=86;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta("I","q",$cast(java.lang.String.class,"")),new Object[]{"$E"});
      $line=87;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta("q","F",$cast(java.lang.String.class,"")),new Object[]{"$"});
      $line=89;
      for (Object $v1:GCollections.unmodifiableCollection(GCollections.asSet('(',')','+','*','v','n'))) {
        Object x=$v1;
        $line=90;
        $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta("q","q",$cast(java.lang.String.class,$opAdditY("",x))),new Object[]{$opAdditY("",x)});
      }
      $line=92;
      $invokeMethod("changeTop",((gold.structures.automaton.GPushdownAutomaton)M).delta("q","q",$cast(java.lang.String.class,"")),new Object[]{"E","v"});
      $line=93;
      $invokeMethod("changeTop",((gold.structures.automaton.GPushdownAutomaton)M).delta("q","q",$cast(java.lang.String.class,"")),new Object[]{"E","n"});
      $line=94;
      $invokeMethod("changeTop",((gold.structures.automaton.GPushdownAutomaton)M).delta("q","q",$cast(java.lang.String.class,"")),new Object[]{"E",")L+("});
      $line=95;
      $invokeMethod("changeTop",((gold.structures.automaton.GPushdownAutomaton)M).delta("q","q",$cast(java.lang.String.class,"")),new Object[]{"E",")L*("});
      $line=96;
      $invokeMethod("changeTop",((gold.structures.automaton.GPushdownAutomaton)M).delta("q","q",$cast(java.lang.String.class,"")),new Object[]{"L","E"});
      $line=97;
      $invokeMethod("changeTop",((gold.structures.automaton.GPushdownAutomaton)M).delta("q","q",$cast(java.lang.String.class,"")),new Object[]{"L","EL"});
      $line=98;
      $result=M;
      if (true) break $try;
      $line=99;
      $rethrow(new RuntimeException("The function \"createAutomaton()\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,LexerParser.class,"createAutomaton",$line);
    }
    return $cast(IPushdownAutomaton.class,$result);
  }
  public static IPushdownAutomaton createAutomaton2() {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=113;
      Object Terms=$fix(GCollections.asSet('(',')','+','*','v','n'));
      $line=114;
      Object NonTerms=$fix(GCollections.asSet('E','L'));
      $line=115;
      Object Q=$fix(GCollections.asSet("I","F"));
      $line=116;
      Object \u03A3=$fix(GCollections.asSet('(',')','+','*','v','n'));
      $line=117;
      Object \u0393=$fix(GCollections.asSet('1'));
      $line=118;
      Object q_0=$fix("I");
      $line=119;
      Object F=$fix(GCollections.asSet("F"));
      $line=120;
      Object M=$fix($invokeConstructor(GPushdownAutomaton.class,new Object[]{Q,\u03A3,\u0393,q_0,F}));
      $line=122;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta("I","I",$cast(java.lang.String.class,"(+")),new Object[]{"1"});
      $line=123;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta("I","I",$cast(java.lang.String.class,"(*")),new Object[]{"1"});
      $line=124;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta("I","F",$cast(java.lang.String.class,"v")),new Object[]{});
      $line=125;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta("I","F",$cast(java.lang.String.class,"n")),new Object[]{});
      $line=126;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta("F","F",$cast(java.lang.String.class,")")),new Object[]{"1"});
      $line=127;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta("F","I",$cast(java.lang.String.class,"")),new Object[]{});
      $line=130;
      $result=M;
      if (true) break $try;
      $line=131;
      $rethrow(new RuntimeException("The function \"createAutomaton2()\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,LexerParser.class,"createAutomaton2",$line);
    }
    return $cast(IPushdownAutomaton.class,$result);
  }
  public static ITransducer createTransducer() {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=140;
      Object Q=$fix(GCollections.asSet("I","Id","p","p_","p_r","p_re","p_red","f","fi","fin","fin_","fin_r","fin_re","fin_red","c","ca","cap","capa","capac","capaci","capacid","capacida","capacidad","capacidad:","capacidad:=","m","ma","mar","marc","marca","marcac","marcaci","marcacio","marcacion","marcacion_","marcacion_i","marcacion_i:","marcacion_i:=","v","va","var","Nom","s","si","sit","siti","sitio","sitio:","=","Num","Err"));
      $line=145;
      Object \u03A3=$fix($opUnionY($opUnionY($opIntvlY('a','z'),$opIntvlY('0','9')),GCollections.asSet('_',' ','=',':')));
      $line=146;
      Object Out=$fix(GCollections.asSet('P','n','F','V','S','C','I','Q','=','#',':'));
      $line=147;
      Object q_0=$fix("I");
      $line=148;
      Object F=$fix(GCollections.asSet("I"));
      $line=149;
      $result=$invokeConstructor(GDeterministicTransducer.class,new Object[]{Q,\u03A3,Out,q_0,F,new GMethod(LexerParser.class,"\u03B4"),new GMethod(LexerParser.class,"g"),new GMethod(LexerParser.class,"h")});
      if (true) break $try;
      $line=150;
      $rethrow(new RuntimeException("The function \"createTransducer()\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,LexerParser.class,"createTransducer",$line);
    }
    return $cast(ITransducer.class,$result);
  }
  public static Object \u03B4(Object q, Object \u03C3) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=153;
      if ($bool($opEqualY(q,"Err"))) {
        $line=153;
        $result="Err";
        if (true) break $try;
      }
      else {
        $line=154;
        if (($opEqualY(q,"I")&&$opEqualY(\u03C3,'='))) {
          $line=154;
          $result="=";
          if (true) break $try;
        }
        else {
          $line=156;
          if (($opEqualY(q,"I")&&$opEqualY(\u03C3,'p'))) {
            $line=156;
            $result="p";
            if (true) break $try;
          }
          else {
            $line=157;
            if (($opEqualY(q,"p")&&$opEqualY(\u03C3,'_'))) {
              $line=157;
              $result="p_";
              if (true) break $try;
            }
            else {
              $line=158;
              if (($opEqualY(q,"p_")&&$opEqualY(\u03C3,'r'))) {
                $line=158;
                $result="p_r";
                if (true) break $try;
              }
              else {
                $line=159;
                if (($opEqualY(q,"p_r")&&$opEqualY(\u03C3,'e'))) {
                  $line=159;
                  $result="p_re";
                  if (true) break $try;
                }
                else {
                  $line=160;
                  if (($opEqualY(q,"p_re")&&$opEqualY(\u03C3,'d'))) {
                    $line=160;
                    $result="p_red";
                    if (true) break $try;
                  }
                  else {
                    $line=162;
                    if (($opEqualY(q,"I")&&$opEqualY(\u03C3,'c'))) {
                      $line=162;
                      $result="c";
                      if (true) break $try;
                    }
                    else {
                      $line=163;
                      if (($opEqualY(q,"c")&&$opEqualY(\u03C3,'a'))) {
                        $line=163;
                        $result="ca";
                        if (true) break $try;
                      }
                      else {
                        $line=164;
                        if (($opEqualY(q,"ca")&&$opEqualY(\u03C3,'p'))) {
                          $line=164;
                          $result="cap";
                          if (true) break $try;
                        }
                        else {
                          $line=165;
                          if (($opEqualY(q,"cap")&&$opEqualY(\u03C3,'a'))) {
                            $line=165;
                            $result="capa";
                            if (true) break $try;
                          }
                          else {
                            $line=166;
                            if (($opEqualY(q,"capa")&&$opEqualY(\u03C3,'c'))) {
                              $line=166;
                              $result="capac";
                              if (true) break $try;
                            }
                            else {
                              $line=167;
                              if (($opEqualY(q,"capac")&&$opEqualY(\u03C3,'i'))) {
                                $line=167;
                                $result="capaci";
                                if (true) break $try;
                              }
                              else {
                                $line=168;
                                if (($opEqualY(q,"capaci")&&$opEqualY(\u03C3,'d'))) {
                                  $line=168;
                                  $result="capacid";
                                  if (true) break $try;
                                }
                                else {
                                  $line=169;
                                  if (($opEqualY(q,"capacid")&&$opEqualY(\u03C3,'a'))) {
                                    $line=169;
                                    $result="capacida";
                                    if (true) break $try;
                                  }
                                  else {
                                    $line=170;
                                    if (($opEqualY(q,"capacida")&&$opEqualY(\u03C3,'d'))) {
                                      $line=170;
                                      $result="capacidad";
                                      if (true) break $try;
                                    }
                                    else {
                                      $line=171;
                                      if (($opEqualY(q,"capacidad")&&$opEqualY(\u03C3,':'))) {
                                        $line=171;
                                        $result="capacidad:";
                                        if (true) break $try;
                                      }
                                      else {
                                        $line=172;
                                        if (($opEqualY(q,"capacidad:")&&$opEqualY(\u03C3,'='))) {
                                          $line=172;
                                          $result="capacidad:=";
                                          if (true) break $try;
                                        }
                                        else {
                                          $line=174;
                                          if (($opEqualY(q,"I")&&$opEqualY(\u03C3,'m'))) {
                                            $line=174;
                                            $result="m";
                                            if (true) break $try;
                                          }
                                          else {
                                            $line=175;
                                            if (($opEqualY(q,"m")&&$opEqualY(\u03C3,'a'))) {
                                              $line=175;
                                              $result="ma";
                                              if (true) break $try;
                                            }
                                            else {
                                              $line=176;
                                              if (($opEqualY(q,"ma")&&$opEqualY(\u03C3,'r'))) {
                                                $line=176;
                                                $result="mar";
                                                if (true) break $try;
                                              }
                                              else {
                                                $line=177;
                                                if (($opEqualY(q,"mar")&&$opEqualY(\u03C3,'c'))) {
                                                  $line=177;
                                                  $result="marc";
                                                  if (true) break $try;
                                                }
                                                else {
                                                  $line=178;
                                                  if (($opEqualY(q,"marc")&&$opEqualY(\u03C3,'a'))) {
                                                    $line=178;
                                                    $result="marca";
                                                    if (true) break $try;
                                                  }
                                                  else {
                                                    $line=179;
                                                    if (($opEqualY(q,"marca")&&$opEqualY(\u03C3,'c'))) {
                                                      $line=179;
                                                      $result="marcac";
                                                      if (true) break $try;
                                                    }
                                                    else {
                                                      $line=180;
                                                      if (($opEqualY(q,"marcac")&&$opEqualY(\u03C3,'i'))) {
                                                        $line=180;
                                                        $result="marcaci";
                                                        if (true) break $try;
                                                      }
                                                      else {
                                                        $line=181;
                                                        if (($opEqualY(q,"marcaci")&&$opEqualY(\u03C3,'o'))) {
                                                          $line=181;
                                                          $result="marcacio";
                                                          if (true) break $try;
                                                        }
                                                        else {
                                                          $line=182;
                                                          if (($opEqualY(q,"marcacio")&&$opEqualY(\u03C3,'n'))) {
                                                            $line=182;
                                                            $result="marcacion";
                                                            if (true) break $try;
                                                          }
                                                          else {
                                                            $line=183;
                                                            if (($opEqualY(q,"marcacion")&&$opEqualY(\u03C3,'_'))) {
                                                              $line=183;
                                                              $result="marcacion_";
                                                              if (true) break $try;
                                                            }
                                                            else {
                                                              $line=184;
                                                              if (($opEqualY(q,"marcacion_")&&$opEqualY(\u03C3,'i'))) {
                                                                $line=184;
                                                                $result="marcacion_i";
                                                                if (true) break $try;
                                                              }
                                                              else {
                                                                $line=185;
                                                                if (($opEqualY(q,"marcacion_i")&&$opEqualY(\u03C3,':'))) {
                                                                  $line=185;
                                                                  $result="marcacion_i:";
                                                                  if (true) break $try;
                                                                }
                                                                else {
                                                                  $line=186;
                                                                  if (($opEqualY(q,"marcacion_i:")&&$opEqualY(\u03C3,'='))) {
                                                                    $line=186;
                                                                    $result="marcacion_i:=";
                                                                    if (true) break $try;
                                                                  }
                                                                  else {
                                                                    $line=188;
                                                                    if (($opEqualY(q,"I")&&$opEqualY(\u03C3,'s'))) {
                                                                      $line=188;
                                                                      $result="s";
                                                                      if (true) break $try;
                                                                    }
                                                                    else {
                                                                      $line=189;
                                                                      if (($opEqualY(q,"s")&&$opEqualY(\u03C3,'i'))) {
                                                                        $line=189;
                                                                        $result="si";
                                                                        if (true) break $try;
                                                                      }
                                                                      else {
                                                                        $line=190;
                                                                        if (($opEqualY(q,"si")&&$opEqualY(\u03C3,'t'))) {
                                                                          $line=190;
                                                                          $result="sit";
                                                                          if (true) break $try;
                                                                        }
                                                                        else {
                                                                          $line=191;
                                                                          if (($opEqualY(q,"sit")&&$opEqualY(\u03C3,'i'))) {
                                                                            $line=191;
                                                                            $result="siti";
                                                                            if (true) break $try;
                                                                          }
                                                                          else {
                                                                            $line=192;
                                                                            if (($opEqualY(q,"siti")&&$opEqualY(\u03C3,'o'))) {
                                                                              $line=192;
                                                                              $result="sitio";
                                                                              if (true) break $try;
                                                                            }
                                                                            else {
                                                                              $line=193;
                                                                              if (($opEqualY(q,"sitio")&&$opEqualY(\u03C3,':'))) {
                                                                                $line=193;
                                                                                $result="sitio:";
                                                                                if (true) break $try;
                                                                              }
                                                                              else {
                                                                                $line=194;
                                                                                if (($opEqualY(q,"sitio:")&&$opEqualY(\u03C3,' '))) {
                                                                                  $line=194;
                                                                                  $result="Nom";
                                                                                  if (true) break $try;
                                                                                }
                                                                                else {
                                                                                  $line=198;
                                                                                  if (($opEqualY(q,"I")&&$opEqualY(\u03C3,'f'))) {
                                                                                    $line=198;
                                                                                    $result="f";
                                                                                    if (true) break $try;
                                                                                  }
                                                                                  else {
                                                                                    $line=199;
                                                                                    if (($opEqualY(q,"f")&&$opEqualY(\u03C3,'i'))) {
                                                                                      $line=199;
                                                                                      $result="fi";
                                                                                      if (true) break $try;
                                                                                    }
                                                                                    else {
                                                                                      $line=200;
                                                                                      if (($opEqualY(q,"fi")&&$opEqualY(\u03C3,'n'))) {
                                                                                        $line=200;
                                                                                        $result="fin";
                                                                                        if (true) break $try;
                                                                                      }
                                                                                      else {
                                                                                        $line=201;
                                                                                        if (($opEqualY(q,"fin")&&$opEqualY(\u03C3,'_'))) {
                                                                                          $line=201;
                                                                                          $result="fin_";
                                                                                          if (true) break $try;
                                                                                        }
                                                                                        else {
                                                                                          $line=202;
                                                                                          if (($opEqualY(q,"fin_")&&$opEqualY(\u03C3,'r'))) {
                                                                                            $line=202;
                                                                                            $result="fin_r";
                                                                                            if (true) break $try;
                                                                                          }
                                                                                          else {
                                                                                            $line=203;
                                                                                            if (($opEqualY(q,"fin_r")&&$opEqualY(\u03C3,'e'))) {
                                                                                              $line=203;
                                                                                              $result="fin_re";
                                                                                              if (true) break $try;
                                                                                            }
                                                                                            else {
                                                                                              $line=204;
                                                                                              if (($opEqualY(q,"fin_re")&&$opEqualY(\u03C3,'d'))) {
                                                                                                $line=204;
                                                                                                $result="fin_red";
                                                                                                if (true) break $try;
                                                                                              }
                                                                                              else {
                                                                                                $line=206;
                                                                                                if (($opEqualY(q,"I")&&$opEqualY(\u03C3,'v'))) {
                                                                                                  $line=206;
                                                                                                  $result="v";
                                                                                                  if (true) break $try;
                                                                                                }
                                                                                                else {
                                                                                                  $line=207;
                                                                                                  if (($opEqualY(q,"v")&&$opEqualY(\u03C3,'a'))) {
                                                                                                    $line=207;
                                                                                                    $result="va";
                                                                                                    if (true) break $try;
                                                                                                  }
                                                                                                  else {
                                                                                                    $line=208;
                                                                                                    if (($opEqualY(q,"va")&&$opEqualY(\u03C3,'r'))) {
                                                                                                      $line=208;
                                                                                                      $result="var";
                                                                                                      if (true) break $try;
                                                                                                    }
                                                                                                    else {
                                                                                                      $line=210;
                                                                                                      if (($opEqualY(q,"I")&&$opMembrY(\u03C3,$opIntvlY('a','z')))) {
                                                                                                        $line=210;
                                                                                                        $result="Nom";
                                                                                                        if (true) break $try;
                                                                                                      }
                                                                                                      else {
                                                                                                        $line=211;
                                                                                                        if (($opEqualY(q,"Nom")&&$opMembrY(\u03C3,$opUnionY($opIntvlY('a','z'),$opIntvlY('0','9'))))) {
                                                                                                          $line=211;
                                                                                                          $result="Nom";
                                                                                                          if (true) break $try;
                                                                                                        }
                                                                                                        else {
                                                                                                          $line=213;
                                                                                                          if (($opEqualY(q,"I")&&$opMembrY(\u03C3,$opIntvlY('0','9')))) {
                                                                                                            $line=213;
                                                                                                            $result="Num";
                                                                                                            if (true) break $try;
                                                                                                          }
                                                                                                          else {
                                                                                                            $line=214;
                                                                                                            if (($opEqualY(q,"Num")&&$opMembrY(\u03C3,$opIntvlY('0','9')))) {
                                                                                                              $line=214;
                                                                                                              $result="Num";
                                                                                                              if (true) break $try;
                                                                                                            }
                                                                                                            else {
                                                                                                              $line=216;
                                                                                                              if (($opEqualY(q,"Num")&&$opMembrY(\u03C3,$opIntvlY('a','z')))) {
                                                                                                                $line=216;
                                                                                                                $result="Err";
                                                                                                                if (true) break $try;
                                                                                                              }
                                                                                                              else {
                                                                                                                $line=218;
                                                                                                                if ($opMembrY(\u03C3,GCollections.asSet(' '))) {
                                                                                                                  $line=218;
                                                                                                                  $result="I";
                                                                                                                  if (true) break $try;
                                                                                                                }
                                                                                                                else {
                                                                                                                  $line=220;
                                                                                                                  $result="Id";
                                                                                                                  if (true) break $try;
                                                                                                                }
                                                                                                              }
                                                                                                            }
                                                                                                          }
                                                                                                        }
                                                                                                      }
                                                                                                    }
                                                                                                  }
                                                                                                }
                                                                                              }
                                                                                            }
                                                                                          }
                                                                                        }
                                                                                      }
                                                                                    }
                                                                                  }
                                                                                }
                                                                              }
                                                                            }
                                                                          }
                                                                        }
                                                                      }
                                                                    }
                                                                  }
                                                                }
                                                              }
                                                            }
                                                          }
                                                        }
                                                      }
                                                    }
                                                  }
                                                }
                                              }
                                            }
                                          }
                                        }
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
      $line=222;
      $rethrow(new RuntimeException("The function \"\u03B4(q:Object,\u03C3:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,LexerParser.class,"\u03B4",$line);
    }
    return $result;
  }
  public static Object g(Object q) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=227;
      $result="";
      if (true) break $try;
      $line=228;
      $rethrow(new RuntimeException("The function \"g(q:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,LexerParser.class,"g",$line);
    }
    return $result;
  }
  public static Object h(Object q, Object \u03C3) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=231;
      String s=null;
      s=$defaultValue(String.class);
      $line=232;
      s=$cast(String.class,$fix(""));
      $line=234;
      if ((!$opMembrY(q,GCollections.asSet("Err"))&&$opMembrY(\u03C3,GCollections.asSet(' ')))) {
        $line=236;
        if (!$opMembrY(\u03C3,GCollections.asSet(' '))) {
          $line=236;
          s=$cast(String.class,$fix($invokeMethod(String.class,"valueOf",true,null,new Object[]{\u03C3})));
        }
        $line=238;
        if ($opEqualY(q,"I")) {
          $line=238;
          $result=s;
          if (true) break $try;
        }
        else {
          $line=239;
          if ($opEqualY(q,"p_red")) {
            $line=239;
            $result=$opAdditY("P",s);
            if (true) break $try;
          }
          else {
            $line=240;
            if ($opEqualY(q,"sitio:")) {
              $line=240;
              $result=$opAdditY("S:",s);
              if (true) break $try;
            }
            else {
              $line=241;
              if ($opEqualY(q,"fin_red")) {
                $line=241;
                $result=$opAdditY("F",s);
                if (true) break $try;
              }
              else {
                $line=242;
                if ($opEqualY(q,"var")) {
                  $line=242;
                  $result=$opAdditY("V",s);
                  if (true) break $try;
                }
                else {
                  $line=243;
                  if ($opEqualY(q,"capacidad:=")) {
                    $line=243;
                    $result=$opAdditY("CQ",s);
                    if (true) break $try;
                  }
                  else {
                    $line=244;
                    if ($opEqualY(q,"marcacion_i:=")) {
                      $line=244;
                      $result=$opAdditY("IQ",s);
                      if (true) break $try;
                    }
                    else {
                      $line=246;
                      if (($opEqualY(q,"=")&&$opEqualY(\u03C3,' '))) {
                        $line=246;
                        $result=$opAdditY("=",s);
                        if (true) break $try;
                      }
                      else {
                        $line=249;
                        if ($opEqualY(q,"Nom")) {
                          $line=249;
                          $result=$opAdditY("n",s);
                          if (true) break $try;
                        }
                        else {
                          $line=250;
                          if ($opEqualY(q,"Num")) {
                            $line=250;
                            $result=$opAdditY("#",s);
                            if (true) break $try;
                          }
                          else {
                            $line=251;
                            $result=s;
                            if (true) break $try;
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
      else {
        $line=253;
        $result="";
        if (true) break $try;
      }
      $line=256;
      $rethrow(new RuntimeException("The function \"h(q:Object,\u03C3:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,LexerParser.class,"h",$line);
    }
    return $result;
  }
}
